version: '3.8'

services:
  frontend:
    build: ./frontend
    ports:
      - "3000:3000"
    depends_on:
      - backend

  backend:
    build: ./backend
    ports:
      - "5000:5000"

  node-red:
    image: nodered/node-red
    ports:
      - "1880:1880"
    volumes:
      - ./iot-simulation/node-red:/data
